### PR TITLE
Smol upgrade

### PR DESCRIPTION
**Pull request by Kovalenko2002**
Is not much, may fail on many other computer but is like smol upgrade. On smol thing.
1eb3cbda4c0d96c8981b0ab37112a27d

### CODE REVIEW

**Comment by louisbui63** [comment]
I really don't think we should manage installs like that, all it's going to do is frustrate users of non-debian based systems. I guess we could provide an AUR package and maybe a .deb though.
I think there might be a licensing issue with the "no internet" image since we are distributing it directly ?
I will look into it more tomorrow but other than that it should be good to merge

**Comment by louisbui63** [comment]
I guess you should also add `coreutils` to the dependencies since you use `base64`

**Comment by Kovalenko2002** [comment]
Was wondering about some modification :

Transfer the fetched images in .autocatgirl so that the last fetched one can appear when restarting you pc.
Modify a bit so that you can keep the seen one and the loaded one.

With the actual structure adding a favorite path works but exporting the image exports the newly loaded one.

**Comment by louisbui63** [comment]
I agree that the images should probably not be stored in `/tmp`, it has a tendency to break things at restart anyway. 

Concerning the problem with the image you want to add to your favourites having been already replaced, I guess you could just keep the file for the previous image?

I did some digging on the "no internet access" image and the artist's tumblr's says "Please do not edit/repost the drawings" so we won't be able to use it.

**Comment by Kovalenko2002** [comment]
Yeah I'll find an alternative to jump between the 2.

About the image I'll either remove the functionality (since the stored image is not in temporary it can fall back to it) or find one that can be used.

**Pull request closed without merging**
